### ISSUE TITLE
colorpanes as replacement for `src/candy/panes.sh`

### ISSUE THREAD

**Issue by auroraanna** [Kqpa/.shell-scripts#1]
I made the [colorpanes](https://codeberg.org/papojari/colorpanes) program to replace panes scripts such as yours and copies like it. Are you interested in replacing the script with colorpanes?

## Benefits of colorpanes opposed to panes.sh:
  - foreground and background color to have a shadow
  - ability to control height and width of colorpanes
  - select between horizontal and vertical colorpanes
  - ability to remove margin
  - ability to add captions
  - made in Rust: memory-safe, fast, code that you can actually understand unlike the panes.sh

**Comment by Kqpa** [comment]
nah dawg, promote your program somewhere else. zeesh’s goal isn’t to make color scripts — it’s to make zsh more user friendly and keeping it easy
